const LOGIN_API = '/api/account/login'
const ACCOUNT = '/api/account'
const USER = '/api/user'
const MATCH_MAKING_RECS = '/api/match-making/recs'
const MATCH_MAKING_LIKE = '/api/match-making/like'
const MATCH_MAKING_NOPE = '/api/match-making/pass'
const MATCH_MAKING_MATCH_LIST = '/api/match-making/matches'
const MEDIA = '/api/media'