export const UPDATE_THEME = 'UPDATE_THEME'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_FAILURE = 'USER_GET_FAILURE'

export const ACCOUNT_GET_REQUEST = 'ACCOUNT_GET_REQUEST'
export const ACCOUNT_GET_SUCCESS = 'ACCOUNT_GET_SUCCESS'
export const ACCOUNT_GET_FAILURE = 'ACCOUNT_GET_FAILURE'

export const PASSION_GET_REQUEST = 'PASSION_GET_REQUEST'
export const PASSION_GET_SUCCESS = 'PASSION_GET_SUCCESS'
export const PASSION_GET_FAILURE = 'PASSION_GET_FAILURE'