export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

export const LOGIN = 'LOGIN'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_FAILURE = 'USER_GET_FAILURE'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'

export const ACCOUNT_GET_REQUEST = 'ACCOUNT_GET_REQUEST'
export const ACCOUNT_GET_SUCCESS = 'ACCOUNT_GET_SUCCESS'
export const ACCOUNT_GET_FAILURE = 'ACCOUNT_GET_FAILURE'

export const ACCOUNT_POST_REQUEST = 'ACCOUNT_POST_REQUEST'
export const ACCOUNT_POST_SUCCESS = 'ACCOUNT_POST_SUCCESS'
export const ACCOUNT_POST_FAILURE = 'ACCOUNT_POST_FAILURE'

export const ACCOUNT_PUT_REQUEST = 'ACCOUNT_PUT_REQUEST'
export const ACCOUNT_PUT_SUCCESS = 'ACCOUNT_PUT_SUCCESS'
export const ACCOUNT_PUT_FAILURE = 'ACCOUNT_PUT_FAILURE'

export const ACCOUNT_DELETE_REQUEST = 'ACCOUNT_DELETE_REQUEST'
export const ACCOUNT_DELETE_SUCCESS = 'ACCOUNT_DELETE_SUCCESS'
export const ACCOUNT_DELETE_FAILURE = 'ACCOUNT_DELETE_FAILURE'

export const PASSION_GET_REQUEST = 'PASSION_GET_REQUEST'
export const PASSION_GET_SUCCESS = 'PASSION_GET_SUCCESS'
export const PASSION_GET_FAILURE = 'PASSION_GET_FAILURE'

export const RECS_LIST_GET_REQUEST = 'RECS_LIST_GET_REQUEST'
export const RECS_LIST_GET_SUCCESS = 'RECS_LIST_GET_SUCCESS'
export const RECS_LIST_GET_FAILURE = 'RECS_LIST_GET_FAILURE'

export const LIKE_REQUEST = 'LIKE_REQUEST'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_FAILURE = 'LIKE_FAILURE'

export const PASS_REQUEST = 'PASS_REQUEST'
export const PASS_SUCCESS = 'PASS_SUCCESS'
export const PASS_FAILURE = 'PASS_FAILURE'